dist: trusty
before_install:
  - sudo apt-get install -y ninja-build
script:
  - git fetch --unshallow || if [ $? -eq 128 ]; then true; else false; fi
  - git rev-list --count HEAD
  - bash -x build.sh
deploy:
  provider: releases
  api_key: $ACCESS_TOKEN
  file:
    - ../Prusa-CW-Firmware/Prusa-CW-Firmware.hex
  skip_cleanup: true
  on:
    tags: true
